### PR TITLE
Add libstdc++6

### LINKED ISSUE #65: Add GLIBCXX_3.4.22 to the base libraries
Hi, the owner of @atom-community here.

The native addons that we make require `GLIBCXX_3.4.22` for the reasons explained here by the [nodejs maintainers](https://github.com/nodejs/node-gyp/issues/2297#issuecomment-755049813). Could you add this library to the snap?

It solves these issues: 
```
At /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/cool/.atom/packages/autocomplete-paths/node_modules/fuzzaldrin-plus-fast/build/Release/fuzzaldrinplusfast.node)
```

https://github.com/nodejs/node-gyp/issues/2297
https://github.com/atom-community/ide-python/issues/255

### PR DESCRIPTION
**Pull request by aminya**
Hopefully, fixes #65

### CODE REVIEW

**Comment by aminya** [comment]
@popey Does this solve the issue? I am not familiar with the syntax of snap config.

I could not find the config for Ubuntu 18, but this library should be added in that config too (if missing).

**Comment by popey** [comment]
Thanks very much for the pull request. I don’t have the ability to reproduce the issue right now. I have published a build of the snap incorporating your fix in a branch. Please could you install the build on a clean system, or if you have the snap already installed, refresh to this branch, and test it?

`snap install atom --channel stable/fix-65`

or:

`snap refresh atom --channel stable/fix-65`

If you’re happy with the fix, I’ll land this PR. 

Thanks again!

**Comment by aminya** [comment]
@popey I ran the tests using this branch, and it seems to work. So, if you can merge this that would be great. I need to get user's feedback too since I am not mainly on Ubuntu.

https://github.com/atom-community/zadeh/runs/1660884233#step:9:11

**Comment by aminya** [comment]
@deedeeg Could you do a test for us? For example, see if `ide-python@v1.7.1` works on this snap Atom.

**Comment by DeeDeeG** [comment]
@aminya I'm looking over the PR and related conversations so I can see what exactly I should expect, what needs testing, and so on.

**Comment by DeeDeeG** [comment]
@aminya once I have `ide-python` installed, and all its requirements (https://github.com/atom-community/ide-python#requirements), how do I open a window/interface of the IDE?

**Comment by aminya** [comment]
> @aminya once I have `ide-python` installed, and all its requirements (https://github.com/atom-community/ide-python#requirements), how do I open a window/interface of the IDE?

If no error similar to #65 is thrown in Atom or in the dev tools then it means it is working.

You can also try autocomplete-path package

**Comment by DeeDeeG** [comment]
I loaded the regular `stable` channel of the Atom snap. (I'm running a Kubuntu 20.10 LiveDVD image in VirtualBox).

With `stable` Atom v1.54.0 snap, I am not seeing any activation errors for these two packages.

(I don't think the person reporting that issue left us clear steps to reproduce, so I'm not sure what problem they were seeing. It almost sounds like they had a really old OS/ old libc, installed a newer OS over it but preserving their home directory... so in their `.atom` folder they had pre-compiled packages with naive binaries compiled for an older system, but trying to run these old binaries on a new system. I bet if they uninstalled and reinstalled the `ide-python` Atom package, the error message would go away... Maybe? Who knows? As I said, the background info (not a lot) and steps to reproduce (none that we can reproduce at the moment) were not great.)

**Comment by DeeDeeG** [comment]
On the positive side: I think their issue is not due to the package or the snap, so it's likely not our responsibility to fix.

Probably the greatest amount of end-user trouble and confusion in the Atom world comes from natively built package binaries that were built against some other target than they are being initialized on...

**Comment by DeeDeeG** [comment]
I had a bunch of nifty language-aware autocomplete suggestions when editing a new file `app.py`. So I think it was working.

**Comment by aminya** [comment]
@popey this PR is ready to merge

**Comment by DeeDeeG** [comment]
@aminya it's working for me on the stable branch of the `atom` snap. I never even got to testing the patched version from this PR because I couldn't reproduce the initial error.

I think my testing implies this PR isn't needed.

**Comment by aminya** [comment]
Maybe you already have the library installed on your machine. 

I still think this PR should be merged.

**Comment by DeeDeeG** [comment]
The person who reported the initial issue said they were "distro hopping" which means installing lots of different Linux OSes. I think they must have installed OSes with two different versions of `libc`. They built this package on one of the OSes, then tried to run it again on the second OS. That seems like a plausible explanation for the error they saw.

I really don't see a way that the Atom snap is related to that issue.

**Comment by DeeDeeG** [comment]
I guess I can try on Ubuntu 20.04.1 instead of Ubuntu 20.10...

**Comment by aminya** [comment]
This issue was reported 13 times by 13 different people. [See all the duplicates I closed](https://github.com/atom-community/ide-python/issues/255). The fact that it does not happen for you does not mean that this library is not needed.

**Comment by DeeDeeG** [comment]
Well I'm also unable to reproduce this on kubuntu 20.04.1, which (20.04.1 in general) is what all the other reports were from.

Sadly I can't test the Atom version they all reported this from, Atom 1.53.0, as the newer version is out 1.54.0, and snap won't let me install the old version unless I have developer access (uploading rights?) to the Atom snap.

I have no idea if this fix is needed or not, and unless someone gives me steps that work for me to actually reproduce the issue it will be unclear to me whether this fix is relevant. I can't say either way based on any evidence or testing.

**Comment by aminya** [comment]
@popey Could you merge this? I have been waiting for it for a long time now.

**Comment by aminya** [comment]
@popey @snapcrafters @flexiondotorg could you merge this?

**Comment by aminya** [comment]
Anyone here?

**Pull request merged**
